variable "aws_region" {
  description = "AWS region the Transfer Family server lives in."
  type        = string
}

variable "server_id" {
  description = "Existing AWS Transfer Family server ID (e.g. s-0123456789abcdef0)."
  type        = string
}

variable "user_name" {
  description = "SFTP user name to create on the Transfer Family server."
  type        = string
}

variable "role_arn" {
  description = "ARN of the existing IAM role the SFTP user assumes (already scoped with GetBucketLocation + DeleteObject, per your setup)."
  type        = string
}

variable "s3_bucket" {
  description = "Target S3 bucket name backing this SFTP user's home directory."
  type        = string
}

variable "home_directory_type" {
  description = "LOGICAL (use home_directory_mappings, recommended) or PATH (use home_directory)."
  type        = string
  default     = "LOGICAL"
}

variable "home_directory" {
  description = "Only used when home_directory_type = PATH. Ignored for LOGICAL."
  type        = string
  default     = "/"
}

variable "home_directory_entry_target" {
  description = "S3 path the user's logical root maps to, e.g. /my-bucket/username. Only used when home_directory_type = LOGICAL."
  type        = string
  default     = ""
}

variable "public_key_path" {
  description = "Local path to the SFTP user's public key file (generated by scripts/generate_ssh_key.sh)."
  type        = string
}

variable "tags" {
  description = "Tags applied to the Transfer Family user resource."
  type        = map(string)
  default     = {}
}
